### ISSUE TITLE
Labels on settings page

### ISSUE THREAD

**Issue by wooorm** [camille500/real-time-web#2]
The following form, inputs, and errors aren’t very helpful:

<img width="365" alt="screen shot 2017-04-29 at 21 22 14" src="https://cloud.githubusercontent.com/assets/944406/25558201/fdbeb128-2d21-11e7-98b3-7df8ddd04ccd.png">

**Comment by camille500** [comment]
Deleted the settings page, now oAuth login only. Setup form (first Twitter login) is with labels
